version: '3'
services:
  nodered:
    image: ghcr.io/lafin/alpine-nodered
    network_mode: host
    environment:
      - SERVICE_NAME=nodered
    volumes:
      - ./nodered:/home/node/.node-red
    depends_on:
      - mosquitto
      - homebridge
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  homebridge:
    image: ghcr.io/lafin/alpine-homebridge
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
    volumes:
      - ./homebridge:/root/.homebridge
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  mosquitto:
    image: ghcr.io/lafin/alpine-mosquitto
    network_mode: host
    environment:
      - SERVICE_NAME=mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"