version: '3'
services:
  nodered:
    network_mode: host
    environment:
      - SERVICE_NAME=nodered
    volumes:
      - ./nodered:/home/node/.node-red
    depends_on:
      - mosquitto
      - homebridge
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  homebridge:
    network_mode: host
    environment:
      - SERVICE_NAME=homebridge
    volumes:
      - ./homebridge:/home/node/.homebridge
    depends_on:
      - mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"
  mosquitto:
    network_mode: host
    environment:
      - SERVICE_NAME=mosquitto
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "2"