name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
jobs:
  actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [nodered, homebridge, mosquitto]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t lafin/alpine-${{ matrix.app }} ${{ matrix.app }}
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/lafin/alpine-${{ matrix.app }}
