name: actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
jobs:
  actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, armhf, arm64]
        app: [nodered, homebridge, mosquitto]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          sed -ie "s/FROM alpine:3.13/FROM multiarch\/alpine:${{ matrix.arch }}\-v3.13/" ${{ matrix.app }}/Dockerfile
          docker build -t lafin/alpine-${{ matrix.app }}:${{ matrix.arch }} ${{ matrix.app }}
      - name: Publish image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u $GITHUB_ACTOR -p ${{ secrets.DOCKER_TOKEN }}
          docker push lafin/alpine-${{ matrix.app }}
